MBergeron dev dualcam
Avnet/hdl pull request #24
Opened 2021-10-18 15:59 UTC by AlbertaBeef

dualcam: add bgr support to capture pipeline, fix base addresses for axi_gpio cores.

2021-10-25 19:34 UTC, narrucmot approved these changes
Wow!  This is a whole lot of changes.

2021-10-26 17:35 UTC, tnizan-witekio approved these changes

2021-10-26 17:42 UTC, tnizan-witekio requested changes

2021-10-26 17:42 UTC, tnizan-witekio commented on boards/u96v2_sbc/dualcam/u96v2_sbc_dualcam.tcl
> +  assign_bd_address -offset 0xA0050000 -range 0x00010000 -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] [get_bd_addr_segs axi_gpio_2/S_AXI/Reg] -force
Due to this PR https://github.com/Avnet/meta-avnet/pull/35/files, I think it would make sense to also hard code this IP address for the base design: boards/u96v2_sbc/base/u96v2_sbc_base.tcl

2021-10-26 18:36 UTC, AlbertaBeef commented on boards/u96v2_sbc/dualcam/u96v2_sbc_dualcam.tcl
> +  assign_bd_address -offset 0xA0050000 -range 0x00010000 -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] [get_bd_addr_segs axi_gpio_2/S_AXI/Reg] -force
Yes, agreed.  Let me make the change and perform a build test.

2021-10-26 19:06 UTC, AlbertaBeef commented on boards/u96v2_sbc/dualcam/u96v2_sbc_dualcam.tcl
> +  assign_bd_address -offset 0xA0050000 -range 0x00010000 -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] [get_bd_addr_segs axi_gpio_2/S_AXI/Reg] -force
Changes have been made.  Verification was performed by confirming that "write_bd_tcl {name}.tcl generates the exact same output.

2021-10-26 19:15 UTC, tnizan-witekio approved these changes

2021-10-27 17:39 UTC, wpatterson-witekio approved these changes
Looks good to me

2021-10-27 17:45 UTC, merged